New script sarcasm.py: Adds random capitalization
weechat/scripts pull request #527
Opened 2023-04-01 08:58 UTC by fsaev

## Script info

- Script name: Sarcasm.py
- Version: 1.0

- Requirements:

- Min WeeChat version: 

- Script tags: display py3

## Description

Adds random capitalization to text to indicate sArCAsm

## Checklist (new script)

- [x] Single commit, single file added
- [x] Commit message: `New script name.py: short description…`
- [x] No similar script already exists
- [x] Name: max 32 chars, only lower case letters, digits and underscores
- [x] Unique name, does not already exist in repository
- [x] No shebang on the first line
- [x] Comment in script with name/pseudo, e-mail and license
- [x] Only English in code/comments
- [x] Pure WeeChat API used, no extra API
- [x] Function `hook_process` is used for any blocking call
- [x] For Python script: works with Python 3 (Python 2 support is optional)
- [x] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

## Checklist (script update)

- [ ] Author has been contacted
- [ ] Single commit, single file added
- [ ] Commit message format: `script_name.py X.Y: …`
- [ ] Script version and Changelog have been updated
- [ ] For Python script: works with Python 3 (Python 2 support is optional)
- [ ] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

## Checklist (script deletion)

- [ ] Author has been contacted
- [ ] Single commit, single file deleted
- [ ] Commit message format: `Remove script name.py` with reasons in description

2023-04-01 19:06 UTC, flashcode requested changes

2023-04-01 19:06 UTC, flashcode commented on python/sarcasm.py
> +        weechat_version = weechat.info_get("version_number", "") or 0
This variable and its initialization are not used, they can be safely removed.

2023-04-01 19:06 UTC, flashcode commented on python/sarcasm.py
> +SCRIPT_NAME = 'sarcasm.py'
By convention the extension should not be part of the script name:

```suggestion
SCRIPT_NAME = 'sarcasm'
```

2023-04-01 19:06 UTC, flashcode commented on python/sarcasm.py
> +# -*- coding: utf-8 -*-
UTF-8 encoding is default in Python 3, so this line is not necessary.

2023-04-01 20:48 UTC, fsaev commented
All fixed! Do you want me to squash it to a single commit as well?

2023-04-02 06:32 UTC, flashcode commented
Yes please squash in a single commit, thanks!

2023-04-02 06:33 UTC, flashcode approved these changes

2023-04-02 13:12 UTC, merged

2023-04-02 13:15 UTC, flashcode commented
Thanks, merged!