New script greentext.py: colorize imageboard-style text formatting
weechat/scripts pull request #546
Opened 2023-10-27 11:12 UTC by agvxov

## Script info

- Script name: greentext
- Version: v1

- Script tags: color, display, py3

## Description
Colorize imageboard-style text formatting.
Both inbound and outbound messages are colored.
Since the coloring uses IRC color codes,
outbound greentexting will be visible to both you and your friends.

The following are supported:
+ greentext
+ purpletext
+ redtext

## Checklist (new script)
- [x] Single commit, single file added
- [x] Commit message: `New script name.py: short description…`
- [x] No similar script already exists
- [x] Name: max 32 chars, only lower case letters, digits and underscores
- [x] Unique name, does not already exist in repository
- [x] No shebang on the first line
- [x] Comment in script with name/pseudo, e-mail and license
- [x] Only English in code/comments
- [x] Pure WeeChat API used, no extra API
- [x] Function `hook_process` is used for any blocking call
- [x] For Python script: works with Python 3 (Python 2 support is optional)
- [x] Score 100 / 100 displayed by [weechat-script-lint](https://github.com/weechat/weechat-script-lint)

2023-10-28 08:30 UTC, flashcode requested changes

2023-10-28 08:30 UTC, flashcode commented on python/greentext.py
> +			weechat.color("purple") + s
`purple` is not a valid WeeChat color (see: https://weechat.org/files/doc/weechat/stable/weechat_user.en.html#command_line_colors), you meant `magenta`?

2023-11-07 18:40 UTC, agvxov commented
Yeah, that was silly of me.
Should be good now.

2023-11-11 12:31 UTC, flashcode approved these changes

2023-11-11 12:31 UTC, merged